configs:
  start_date: '2023-09-29'
  end_date: '2023-09-30'
  destination_folder: 'logs_dredge'
  output_file: 'test1'
  shodan_api_key: '9R6Y860tl9q--------------------------'
  vt_api_key: '5294a7d0ff16------------------046aa2528dc0a4205'

gcp_configs:
  enabled: False
  cred_files: ['logtesting-.json']

aws_configs:
  enabled: False
  profiles: ['demo-env']
  profile_region: 'us-east-1'
  regions: ['us-east-1']

  event_history:
    enabled: False
  guardduty:
    enabled: False
  lb:
    enabled: False
    buckets: ['alb-logs-solidarity-tes']
  waf:
    enabled: False
    buckets: ['aws-waf-logs-solidarity-ops']
  vpc_flow_logs:
    enabled: False
    buckets: ['solidarity-ops-vpn-flow-logs']
  cloudtrail:
    enabled: False
    buckets: ['aws-cloudtrail-logs-065229260063-c8d871e5']
  custom:
    enabled: False
    buckets: ['']
  cloudwatch_logs:
    enabled: False
    log_group_names: ['/aws/eks/eks-test/cluster']

github_configs:
  enabled: False
  access_token: ''
  org_name: ['']
  ent_name: ['']



